name: Create and publish release

on:
  push:
    tags:
    - '*'

env:
  PLUGIN_NAME: darlal-switcher-plus

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run ci

      - name: Create zip distro
        run: |
          pushd ./dist > /dev/null
          zip -r dist.zip ${{ env.PLUGIN_NAME }}
          popd > /dev/null

      - name: Create release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
          artifacts: "dist/dist.zip,dist/${{ env.PLUGIN_NAME }}/*.*"
