name: Run checks
on:
  push:
    branches: [master]
  pull_request_target:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR # from public fork'
        required: true
        type: number

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: |
            ${{
              github.event_name == 'workflow_dispatch' && format('refs/pull/{0}/head', inputs.pr_number)
              || github.event.pull_request.head.sha
              || github.ref
            }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Bundle
        run: npm run bundle

      - name: Package
        run: npm run package-plugin

      - name: Test
        run: npm run test

      - name: Diff PR test coverage vs default branch
        if: github.event_name == 'pull_request_target'
        uses: anuraag016/Jest-Coverage-Diff@V1.4
        with:
          fullCoverageDiff: true
          accessToken: ${{ secrets.DIFF_ACTION_TOKEN }}
          afterSwitchCommand: "npm ci"
          delta: 0.5
